version: "3.8"

services:
  quotify:
    build: .
    container_name: quotify-app
    ports:
      - "8000:19006"   # Expo Web
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - HOST=0.0.0.0
    command: npm start
